// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"geektime/Go-000/Week04/internal/biz"
	"geektime/Go-000/Week04/internal/data"
	"geektime/Go-000/Week04/internal/pkg/grpctransport"
	"geektime/Go-000/Week04/internal/service"
)

// Injectors from wire.go:

func InitializeServer() (*grpctransport.Server, func(), error) {
	db, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(db)
	userUseCase := biz.NewUserUseCase(userRepo)
	userService := service.NewUserService(userUseCase)
	server := grpctransport.NewServer(userService)
	return server, func() {
		cleanup()
	}, nil
}
